---
Name: saltedknowledgehub
After: 'framework/*','cms/*'
---
ContentController:
  extensions:
    - 'PageJSInjector'

DataList:
  extensions:
    - DataListExt

ArrayList:
  extensions:
    - DataListExt
